# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Team_UP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Analytics'
pod 'Firebase/Database'
pod 'GrowingTextView', '0.6.1'
pod 'SnapKit', '~> 5.0.0'

end
